name: Notify Tech Team After First Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  notify-tech-team:
    runs-on: ubuntu-latest
    if: |
      github.event.review.state == 'approved' && 
      github.event.pull_request.approved_reviews_count < 2
    steps:
      - name: Request review from tech team
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PR_TOKEN }}
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              team_reviewers: ['tech_team']  // replace with your actual team name
            });
