name: Notify Tech Team After First Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  notify-tech-team:
    runs-on: ubuntu-latest
    if: |
      github.event.review.state == 'approved' && 
      !contains(github.event.pull_request.requested_teams[*].slug, 'tech_team')
    steps:
      - name: Check reviews and request if needed
        id: check-reviews
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PR_TOKEN }}
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            
            const approvalCount = reviews.filter(review => review.state === 'APPROVED').length;
            
            if (approvalCount < 2) {
              console.log('Adding tech_team as reviewer...');
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                team_reviewers: ['tech_team']
              });
              console.log('Tech team review requested successfully');
            } else {
              console.log('Already has enough approvals, skipping');
            }
            
            // Set status check
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'success',
              description: approvalCount < 2 ? 'Added tech_team as reviewer' : 'Enough approvals present',
              context: 'Review Check'
            });

      - name: Mark job as complete
        run: echo "::set-output name=status::completed"
