name: PR Review Flow -- set labels

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write    # For managing reviews
  issues: write          # For labels

jobs:
  check-required-reviews:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Initial review check
        id: initial-check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const review = context.payload.review;
            
            // Skip if review is not approval
            if (review.state !== 'approved') {
              console.log('Skipping: Not an approval review');
              return 'skip';
            }
            
            return 'continue';

      - name: Get active approvals
        if: steps.initial-check.outputs.result == 'continue'
        id: get-approvals
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            
            // Get active approvals (last review from each user)
            const latestReviews = new Map();
            reviews.forEach(review => {
              latestReviews.set(review.user.login, review);
            });
            const activeApprovals = Array.from(latestReviews.values())
              .filter(review => review.state === 'approved')
              .map(review => review.user.login);
            
            return activeApprovals;

      - name: Read review requirement files
        if: steps.initial-check.outputs.result == 'continue'
        id: read-files
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: codeowners } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: '.github/CODEOWNERS'
            });
            
            const { data: facilitators } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: '.github/CODEFACILITATORS'
            });
            
            const codeownersContent = Buffer.from(codeowners.content, 'base64').toString();
            const facilitatorsContent = Buffer.from(facilitators.content, 'base64').toString();
            
            // Extract usernames/teams from the files
            const codeownersUsers = codeownersContent.match(/@[\w-]+/g) || [];
            const facilitatorsUsers = facilitatorsContent.match(/@[\w-]+/g) || [];
            
            return {
              codeowners: codeownersUsers,
              facilitators: facilitatorsUsers
            };

      - name: Check existing approvals
        if: steps.initial-check.outputs.result == 'continue'
        id: check-existing
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const activeApprovals = JSON.parse(steps.get-approvals.outputs.result);
            const requirements = JSON.parse(steps.read-files.outputs.result);
            
            // Check for facilitator approvals
            const hasFacilitatorApproval = activeApprovals.some(user => 
              requirements.facilitators.includes('@' + user)
            );
            
            // Check for tech-team approvals
            const hasTechTeamApproval = false; // We'll implement this in next step
            
            if (hasFacilitatorApproval || hasTechTeamApproval) {
              console.log('Already has facilitator or tech-team approval, skipping');
              return 'skip';
            }
            
            return 'continue';

      - name: Check approval status
        if: steps.check-existing.outputs.result == 'continue'
        id: check-status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const activeApprovals = JSON.parse(steps.get-approvals.outputs.result);
            const requirements = JSON.parse(steps.read-files.outputs.result);
            
            // Check if all required CODEOWNERS have approved
            const hasAllCodeownersApproval = requirements.codeowners.every(owner => 
              activeApprovals.some(user => '@' + user === owner)
            );
            
            // Check if all required facilitators have approved
            const hasAllFacilitatorsApproval = requirements.facilitators.every(facilitator => 
              activeApprovals.some(user => '@' + user === facilitator)
            );
            
            return {
              codeownersApproved: hasAllCodeownersApproval,
              facilitatorsApproved: hasAllFacilitatorsApproval
            };

      - name: Update labels
        if: steps.check-existing.outputs.result == 'continue'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const status = JSON.parse(steps.check-status.outputs.result);
            
            if (status.codeownersApproved && !status.facilitatorsApproved) {
              console.log('Adding ready-for-facilitators label');
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['ready-for-facilitators']
              });
            }
            
            if (status.codeownersApproved && status.facilitatorsApproved) {
              console.log('Updating labels for tech-team review');
              // Remove facilitators label if it exists
              try {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  name: 'ready-for-facilitators'
                });
              } catch (error) {
                console.log('No facilitators label to remove');
              }
              
              // Add tech-team label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['ready-for-tech-review']
              });
            }
