name: PR Review Flow -- set labels

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write    # For managing reviews
  issues: write          # For labels

jobs:
  check-required-reviews:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Initial review check
        id: initial-check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const review = context.payload.review;
            
            console.log('Current review state:', review.state);
            
            // Skip if review is not approval
            if (review.state !== 'approved') {
              console.log('Skipping: Not an approval review');
              core.setOutput('should_continue', 'false');
              return;
            }
            
            console.log('Approval review detected, continuing...');
            core.setOutput('should_continue', 'true');

      - name: Get active approvals and PR files
        if: steps.initial-check.outputs.should_continue == 'true'
        id: get-approvals
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            console.log('Getting approvals for PR:', pr.number);
            
            // Get PR files
            const { data: prFiles } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            
            const prFilePaths = prFiles.map(file => file.filename);
            console.log('PR files:', prFilePaths);
            
            // Get reviews
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            
            // Get active approvals (last review from each user)
            const latestReviews = new Map();
            reviews.forEach(review => {
              latestReviews.set(review.user.login, review);
            });
            const activeApprovals = Array.from(latestReviews.values())
              .filter(review => review.state === 'approved')
              .map(review => review.user.login);
            
            console.log('Active approvals:', activeApprovals);
            
            core.setOutput('files', JSON.stringify(prFilePaths));
            console.log('Set files output:', JSON.stringify(prFilePaths));
            core.setOutput('approvals', JSON.stringify(activeApprovals));
      
      - name: Read review requirement files
        if: steps.initial-check.outputs.should_continue == 'true'
        id: read-files
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
            const prFiles = JSON.parse('${{ steps.get-approvals.outputs.files }}');
            console.log('PR Files:', prFiles);
            
            // Helper to convert glob to regex
            function globToRegExp(pattern) {
              return new RegExp('^' + pattern
                .replace(/\//g, '\\/') // Escape forward slashes
                .replace(/\*/g, '[^\\/]*') // * matches anything except path separator
                .replace(/\?/g, '[^\\/]') + '$'); // ? matches single char except path separator
            }
      
            const parseOwnersFile = async (path) => {
              const { data: file } = await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: path
              });
              
              const content = Buffer.from(file.content, 'base64').toString();
              const relevantOwners = new Set();
              
              content.split('\n').forEach(line => {
                line = line.trim();
                if (!line || line.startsWith('#')) return;
                
                // First part is the pattern, rest is the team(s)
                const parts = line.split(/\s+/);
                const pattern = parts[0];
                const owners = parts.slice(1);
                
                // Check if any PR files match this pattern
                const regex = globToRegExp(pattern);
                const matches = prFiles.some(file => regex.test(file));
                
                if (matches) {
                  owners.forEach(owner => relevantOwners.add(owner)); // Keep full team name
                }
              });
              
              return Array.from(relevantOwners);
            };
      
            const codeowners = await parseOwnersFile('.github/CODEOWNERS');
            const facilitators = await parseOwnersFile('.github/CODEFACILITATORS');
            
            console.log('Required reviewers:', {
              codeowners,
              facilitators,
              files: prFiles
            });
            
            core.setOutput('requirements', JSON.stringify({
              codeowners,
              facilitators
            }));
            } catch (error) {
              console.error('Error parsing input:', error);
              console.error('Context:', {
                files: '${{ steps.get-approvals.outputs.files }}'
              });
              throw error;
            }

      - name: Check existing approvals
        if: steps.initial-check.outputs.should_continue == 'true'
        id: check-existing
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const activeApprovals = JSON.parse('${{ steps.get-approvals.outputs.approvals }}');
            const requirements = JSON.parse('${{ steps.get-approvals.outputs.requirements }}');
            
            console.log('Checking for existing facilitator/tech-team approvals');
            console.log('Active approvals:', activeApprovals);
            console.log('Requirements:', requirements);
            
            // Check for facilitator approvals
            const hasFacilitatorApproval = activeApprovals.some(user => 
              requirements.facilitators.includes('@' + user)
            );
            
            console.log('Has facilitator approval:', hasFacilitatorApproval);
            
            if (hasFacilitatorApproval) {
              console.log('Already has facilitator approval, skipping further checks');
              core.setOutput('should_continue', 'false');
              return;
            }
            
            core.setOutput('should_continue', 'true');

      - name: Check approval status
        if: steps.check-existing.outputs.should_continue == 'true'
        id: check-status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const activeApprovals = JSON.parse('${{ steps.get-approvals.outputs.approvals }}');
            const requirements = JSON.parse('${{ steps.get-approvals.outputs.requirements }}');
            
            console.log('Checking approval status');
            console.log('Active approvals:', activeApprovals);
            console.log('Requirements:', requirements);
            
            // Check if all required CODEOWNERS have approved
            const hasAllCodeownersApproval = requirements.codeowners.every(owner => 
              activeApprovals.some(user => '@' + user === owner)
            );
            
            // Check if all required facilitators have approved
            const hasAllFacilitatorsApproval = requirements.facilitators.every(facilitator => 
              activeApprovals.some(user => '@' + user === facilitator)
            );
            
            console.log('Approval status:', {
              codeownersApproved: hasAllCodeownersApproval,
              facilitatorsApproved: hasAllFacilitatorsApproval
            });
            
            core.setOutput('status', JSON.stringify({
              codeownersApproved: hasAllCodeownersApproval,
              facilitatorsApproved: hasAllFacilitatorsApproval
            }));

      - name: Update labels
        if: steps.check-existing.outputs.should_continue == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const status = JSON.parse(core.getInput('status'));
            
            console.log('Updating labels based on status:', status);
            
            if (status.codeownersApproved && !status.facilitatorsApproved) {
              console.log('Adding ready-for-facilitators label');
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['ready-for-facilitators']
              });
            }
            
            if (status.codeownersApproved && status.facilitatorsApproved) {
              console.log('Updating labels for tech-team review');
              try {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  name: 'ready-for-facilitators'
                });
                console.log('Removed ready-for-facilitators label');
              } catch (error) {
                console.log('No facilitators label to remove');
              }
              
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['ready-for-tech-review']
              });
              console.log('Added ready-for-tech-review label');
            }
